[workspace]

members = [
    "day1-p1",
    "day1-p2",
    "day2-p1",
    "day2-p2",
    "day3-p1",
    "day3-p2",
    "day4-p1",
    "day4-p2",
    "day5-p1",
    "day5-p2",
    "day6-p1",
    "day6-p2",
    "day7-p1",
    "day7-p2",
]
